#!/usr/bin/env sh

# Scans all TCP ports, and then runs default scripts and version detection on the ones that are open.

# Check if an IP address was provided
if [ -z "$1" ]; then
    echo "Usage: $0 <target_ip>"
    exit 1
fi

target_ip=$1

# Run nmap and save output in greppable format
sudo nmap -p- -oG nmap0 $target_ip > /dev/null
openPorts=$(grep "/open/tcp" nmap0 | awk '{for(i=1;i<=NF;i++) if($i ~ /[0-9]+\/open\/tcp/) print $i}' | cut -d'/' -f1 | paste -sd, -)

# Check if we found any open ports
if [ -n "$openPorts" ]; then
    sudo nmap -sCV -p $openPorts $target_ip -oN nmap1
else
    echo "No open TCP ports found."
fi